name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: gcc main.c
    - name: Install Build Wrapper
      uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4
    - name: Run Build Wrapper
      run: |
       build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} gcc main.c
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
       args: >
         --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
