name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: gcc main.c
    - name: Install Build Wrapper
      uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4
    - name: Run Build Wrapper
      run: |
       build-wrapper-linux-x86-64 --out-dir . gcc main.c
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
       args: >
         --define sonar.cfamily.compile-commands="./compile_commands.json"
    - name: Run PMD
      run: |
         cd .
         wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.9.0/pmd-dist-7.9.0-bin.zip
         unzip pmd-dist-7.9.0-bin.zip
         alias pmd="./pmd-bin-7.9.0/bin/pmd"
         pmd check -d /usr/src -R rulesets/java/quickstart.xml -f text
      shell: bash
      
